//! Build script for `pdf_bridge`.
//!
//! Compiles `cpp/poppler_shim.cc` against the poppler-cpp headers from the
//! source tree at `POPPLER_SRC` (required env var), then links against the
//! system `libpoppler-cpp`.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Locate the poppler source tree.  Set POPPLER_SRC to the directory that
    // contains the top-level `CMakeLists.txt` and `cpp/` sub-directory.
    let poppler_src =
        env::var("POPPLER_SRC").expect("POPPLER_SRC must be set to the poppler source tree root");
    let cpp_include = PathBuf::from(&poppler_src).join("cpp");

    // Rerun if the shim or any poppler-cpp header changes.
    println!("cargo:rerun-if-changed=cpp/poppler_shim.cc");
    println!("cargo:rerun-if-env-changed=POPPLER_SRC");
    println!("cargo:rerun-if-changed={}", cpp_include.display());

    // `poppler_cpp_export.h` is generated by CMake and not present in the raw
    // source tree.  Write a stub into OUT_DIR that defines the export macro as
    // empty (we're building a static shim, not exporting symbols from a DLL).
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set by cargo"));
    let export_stub = out_dir.join("poppler_cpp_export.h");
    fs::write(
        &export_stub,
        "#pragma once\n#define POPPLER_CPP_EXPORT\n#define POPPLER_CPP_EXPORT_DEPRECATED\n",
    )
    .expect("failed to write poppler_cpp_export.h stub");

    // Compile the C++ shim, including the stub export header before the real headers.
    cc::Build::new()
        .cpp(true)
        .std("c++17")
        // out_dir first so our stub `poppler_cpp_export.h` is found before any
        // system-installed version.
        .include(&out_dir)
        .include(&cpp_include)
        // Also include the poppler root for config.h / poppler-config.h.
        .include(&poppler_src)
        .file("cpp/poppler_shim.cc")
        .warnings(false) // poppler headers generate warnings; suppress them
        .compile("poppler_shim");

    // If the -dev package is installed there will be an unversioned .so symlink
    // that the linker can use directly.  When only the runtime library is
    // installed we have to point the linker at it ourselves.
    //
    // We use `dpkg-architecture` to get the multiarch tuple portably (works on
    // any Debian/Ubuntu variant).  Fall back to the bare /usr/lib path on other
    // systems (e.g. Alpine, Fedora).
    let lib_dir = multiarch_lib_dir();

    if !lib_dir.join("libpoppler-cpp.so").exists() {
        // Create symlinks in OUT_DIR pointing at the versioned runtime library
        // so the linker can resolve `-lpoppler-cpp` and `-lpoppler`.
        let pairs = [
            ("libpoppler-cpp.so.0", "libpoppler-cpp.so"),
            ("libpoppler.so.134", "libpoppler.so"),
        ];
        for (target_name, link_name) in pairs {
            let target = lib_dir.join(target_name);
            let link = out_dir.join(link_name);
            if !link.exists() {
                // The versioned library is also missing — fail loudly so
                // the developer knows exactly what to install.
                assert!(
                    target.exists(),
                    "libpoppler runtime library not found at {}: \
                     install libpoppler-cpp-dev or libpoppler-cpp0t64",
                    target.display()
                );
                std::os::unix::fs::symlink(&target, &link).unwrap_or_else(|e| {
                    panic!(
                        "failed to create linker symlink {} → {}: {e}",
                        link.display(),
                        target.display()
                    );
                });
            }
        }
        println!("cargo:rustc-link-search=native={}", out_dir.display());
    }

    // Link against libpoppler-cpp and its dependency libpoppler.
    println!("cargo:rustc-link-lib=dylib=poppler-cpp");
    println!("cargo:rustc-link-lib=dylib=poppler");
}

/// Return the system library directory, using the multiarch tuple on Debian/Ubuntu.
fn multiarch_lib_dir() -> PathBuf {
    // `dpkg-architecture` is Debian/Ubuntu specific but harmless to probe.
    if let Ok(out) = std::process::Command::new("dpkg-architecture")
        .arg("-qDEB_HOST_MULTIARCH")
        .output()
        && out.status.success()
    {
        let tuple = String::from_utf8_lossy(&out.stdout).trim().to_owned();
        if !tuple.is_empty() {
            return PathBuf::from(format!("/usr/lib/{tuple}"));
        }
    }
    PathBuf::from("/usr/lib")
}
