//! Build script for `pdf_bridge`.
//!
//! Compiles `cpp/poppler_shim.cc` against the poppler-cpp headers from the
//! source tree at `POPPLER_SRC` (default: `/home/tom/pdftoppm`), then links
//! against the system `libpoppler-cpp`.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Locate the poppler source tree.  The environment variable allows CI to
    // override the default path.
    let poppler_src = env::var("POPPLER_SRC").unwrap_or_else(|_| "/home/tom/pdftoppm".to_owned());
    let cpp_include = PathBuf::from(&poppler_src).join("cpp");

    // Rerun if the shim or any poppler-cpp header changes.
    println!("cargo:rerun-if-changed=cpp/poppler_shim.cc");
    println!("cargo:rerun-if-env-changed=POPPLER_SRC");
    println!("cargo:rerun-if-changed={}", cpp_include.display());

    // `poppler_cpp_export.h` is generated by CMake and not present in the raw
    // source tree.  Write a stub into OUT_DIR that defines the export macro as
    // empty (we're building a static shim, not exporting symbols from a DLL).
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let export_stub = out_dir.join("poppler_cpp_export.h");
    fs::write(
        &export_stub,
        "#pragma once\n#define POPPLER_CPP_EXPORT\n#define POPPLER_CPP_EXPORT_DEPRECATED\n",
    )
    .expect("failed to write poppler_cpp_export.h stub");

    // Compile the C++ shim, including the stub export header before the real headers.
    cc::Build::new()
        .cpp(true)
        .std("c++17")
        // out_dir first so our stub `poppler_cpp_export.h` is found before any
        // system-installed version.
        .include(&out_dir)
        .include(&cpp_include)
        // Also include the poppler root for config.h / poppler-config.h.
        .include(&poppler_src)
        .file("cpp/poppler_shim.cc")
        .warnings(false) // poppler headers generate warnings; suppress them
        .compile("poppler_shim");

    // Prefer the unversioned .so (provided by -dev package) but fall back to
    // creating a symlink in OUT_DIR so the linker can find the versioned library.
    let lib_dir = PathBuf::from("/usr/lib/x86_64-linux-gnu");
    if !lib_dir.join("libpoppler-cpp.so").exists() {
        // Create symlinks in OUT_DIR that the linker will accept.
        for (target, link_name) in [
            ("libpoppler-cpp.so.0", "libpoppler-cpp.so"),
            ("libpoppler.so.134", "libpoppler.so"),
        ] {
            let link = out_dir.join(link_name);
            if !link.exists() {
                let src = lib_dir.join(target);
                std::os::unix::fs::symlink(&src, &link)
                    .unwrap_or_else(|e| panic!("failed to create symlink {} → {}: {e}", link.display(), src.display()));
            }
        }
        println!("cargo:rustc-link-search=native={}", out_dir.display());
    }

    // Link against libpoppler-cpp and its dependency libpoppler.
    println!("cargo:rustc-link-lib=dylib=poppler-cpp");
    println!("cargo:rustc-link-lib=dylib=poppler");
}
