#!/usr/bin/env python3
"""Pivot v0.9.0 mode-files into a markdown matrix.

Reads bench/v090/{A,D,H,V}.txt — each is stdout of
`tests/bench_corpus.sh --backend X`, rows like:
    01-native-text-small   49ms ±  1ms  95%  99%  12 MB/s
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

CORPORA = [
    ("01-native-text-small",    "01 native text small"),
    ("02-native-vector-text",   "02 native vector+text"),
    ("03-native-text-dense",    "03 native text dense"),
    ("04-ebook-mixed",          "04 ebook mixed"),
    ("05-academic-book",        "05 academic book"),
    ("06-modern-layout-dct",    "06 modern layout DCT"),
    ("07-journal-dct-heavy",    "07 journal DCT heavy"),
    ("08-scan-dct-1927",        "08 scan DCT 1927 (baseline JPEG)"),
    ("09-scan-dct-1836",        "09 scan DCT 1836 (progressive JPEG)"),
    ("10-scan-jbig2-jpx",       "10 scan JBIG2+JPX"),
]

MODES = [
    ("A", "A. CPU-only"),
    ("D", "D. CUDA + nvJPEG"),
    ("H", "H. CUDA parallel-Huffman"),
    ("V", "V. Vulkan parallel-Huffman"),
]

ROW_RE = re.compile(
    r"^(?P<corpus>\S+)\s+(?P<mean>\d+)ms\s+±\s*(?P<stddev>\d+)ms"
    r"(?:\s+(?P<cpu_avg>\S+)%\s+(?P<cpu_peak>\S+)%\s+(?P<disk>\S+)\s+MB/s)?"
    r"(?:\s+(?P<flags>\[.*\]))?\s*$"
)

# v0.8.0 mode A results used as regression baseline.
V080_MODE_A = {
    "01-native-text-small":   41,
    "02-native-vector-text":  18,
    "03-native-text-dense":  217,
    "04-ebook-mixed":        260,
    "05-academic-book":      552,
    "06-modern-layout-dct": 1427,
    "07-journal-dct-heavy":  720,
    "08-scan-dct-1927":     1579,
    "09-scan-dct-1836":     2095,
    "10-scan-jbig2-jpx":   17410,
}


def parse_mode_file(path: Path) -> dict[str, dict]:
    out: dict[str, dict] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        out[m["corpus"]] = {
            "cell": f"{m['mean']}±{m['stddev']}ms",
            "mean": int(m["mean"]),
            "flags": (m["flags"] or "").strip(),
        }
    if not out:
        print(f"warning: {path} exists but yielded no parseable rows", file=sys.stderr)
    return out


def ratio_cell(num: int | None, den: int | None) -> str:
    if num is None or den is None or den == 0:
        return "—"
    return f"{num / den:.2f}×"


def main(in_dir: str) -> int:
    base = Path(in_dir)
    parsed = {mid: parse_mode_file(base / f"{mid}.txt") for mid, _ in MODES}

    print("# v0.9.0 four-mode benchmark — Vulkan vs CUDA parallel-Huffman")
    print()
    print(
        "Generated by `scripts/bench_v090.sh` + `scripts/aggregate_v090.py` "
        "from per-mode output of `tests/bench_corpus.sh`."
    )
    print()
    print(
        "Cells show `mean±stddev` in milliseconds. "
        "H/A = CUDA-Huffman / CPU. V/A = Vulkan-Huffman / CPU. "
        "V/H = Vulkan / CUDA-Huffman (< 1.0 = Vulkan wins)."
    )
    print()

    mode_headers = " | ".join(label for _, label in MODES)
    print(f"| Corpus | {mode_headers} | H/A | V/A | V/H | Flags |")
    sep = " | ".join("---" for _ in MODES)
    print(f"| --- | {sep} | --- | --- | --- | --- |")

    v_wins = 0

    for slug, label in CORPORA:
        cells = []
        flags_parts = []
        for mid, _ in MODES:
            entry = parsed[mid].get(slug)
            cells.append(entry["cell"] if entry else "—")
            if entry and entry["flags"]:
                flags_parts.append(f"{mid}:{entry['flags']}")

        a_mean = (parsed["A"].get(slug) or {}).get("mean")
        h_mean = (parsed["H"].get(slug) or {}).get("mean")
        v_mean = (parsed["V"].get(slug) or {}).get("mean")

        h_a = ratio_cell(h_mean, a_mean)
        v_a = ratio_cell(v_mean, a_mean)
        v_h = ratio_cell(v_mean, h_mean)

        if v_mean is not None and h_mean is not None and v_mean <= h_mean:
            v_wins += 1

        cell_str = " | ".join(cells)
        flags_str = " ".join(flags_parts)
        print(f"| {label} | {cell_str} | {h_a} | {v_a} | {v_h} | {flags_str} |")

    print()
    print("## Regression vs v0.8.0 mode A")
    print()
    print("| Corpus | v0.8.0 A | v0.9.0 A | Δ |")
    print("|---|---|---|---|")
    regress_fail = 0
    for slug, label in CORPORA:
        baseline = V080_MODE_A.get(slug)
        entry = parsed["A"].get(slug)
        if baseline is None or entry is None:
            print(f"| {label} | — | — | — |")
            continue
        cur = entry["mean"]
        delta_pct = (cur - baseline) / baseline * 100
        flag = " **REGRESS**" if delta_pct > 5.0 else ""
        if delta_pct > 5.0:
            regress_fail += 1
        print(f"| {label} | {baseline}ms | {cur}ms | {delta_pct:+.1f}%{flag} |")

    print()
    print("## Summary")
    print()
    print(f"- Vulkan ≤ CUDA-Huffman on {v_wins}/10 corpora")
    print(f"- No corpus regresses > 5% vs v0.8.0 mode A: "
          f"{'PASS' if regress_fail == 0 else f'FAIL ({regress_fail} regressions)'}")
    print()
    print(
        "Note: `GPU_JPEG_HUFFMAN_THRESHOLD_PX = u32::MAX` — the parallel-Huffman "
        "path is not auto-enabled in production. These results are architecture "
        "validation, not production dispatch numbers."
    )
    return 0 if regress_fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "bench/v090"))
