#!/usr/bin/env python3
"""Pivot v0.9.1 mode-files into a markdown matrix.

Reads bench/v091/{A,C-std,C-huff,V-std,V-huff}.txt — each is stdout of
`tests/bench_corpus.sh --backend X`, rows like:
    01-native-text-small   49ms ±  1ms  95%  99%  12 MB/s
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

CORPORA = [
    ("01-native-text-small",    "01 native text small"),
    ("02-native-vector-text",   "02 native vector+text"),
    ("03-native-text-dense",    "03 native text dense"),
    ("04-ebook-mixed",          "04 ebook mixed"),
    ("05-academic-book",        "05 academic book"),
    ("06-modern-layout-dct",    "06 modern layout DCT"),
    ("07-journal-dct-heavy",    "07 journal DCT heavy"),
    ("08-scan-dct-1927",        "08 scan DCT 1927 (baseline JPEG)"),
    ("09-scan-dct-1836",        "09 scan DCT 1836 (progressive JPEG)"),
    ("10-scan-jbig2-jpx",       "10 scan JBIG2+JPX"),
]

# Column order: A baseline, then CUDA pair, then Vulkan pair.
MODES = [
    ("A",      "A. CPU-only"),
    ("C-std",  "C-std. CUDA+nvJPEG"),
    ("C-huff", "C-huff. CUDA Huffman"),
    ("V-std",  "V-std. Vulkan (CPU JPEG)"),
    ("V-huff", "V-huff. Vulkan Huffman"),
]

ROW_RE = re.compile(
    r"^(?P<corpus>\S+)\s+(?P<mean>\d+)ms\s+±\s*(?P<stddev>\d+)ms"
    r"(?:\s+(?P<cpu_avg>\S+)%\s+(?P<cpu_peak>\S+)%\s+(?P<disk>\S+)\s+MB/s)?"
    r"(?:\s+(?P<flags>\[.*\]))?\s*$"
)

# v0.9.0 mode A results used as CPU regression baseline.
V090_MODE_A = {
    "01-native-text-small":   39,
    "02-native-vector-text":  17,
    "03-native-text-dense":  212,
    "04-ebook-mixed":        256,
    "05-academic-book":      562,
    "06-modern-layout-dct": 1429,
    "07-journal-dct-heavy":  768,
    "08-scan-dct-1927":     1675,
    "09-scan-dct-1836":     2171,
    "10-scan-jbig2-jpx":   17810,
}


def parse_mode_file(path: Path) -> dict[str, dict]:
    out: dict[str, dict] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        out[m["corpus"]] = {
            "cell": f"{m['mean']}±{m['stddev']}ms",
            "mean": int(m["mean"]),
            "flags": (m["flags"] or "").strip(),
        }
    if not out:
        print(f"warning: {path} exists but yielded no parseable rows", file=sys.stderr)
    return out


def ratio_cell(num: int | None, den: int | None) -> str:
    if num is None or den is None or den == 0:
        return "—"
    return f"{num / den:.2f}×"


def main(in_dir: str) -> int:
    base = Path(in_dir)
    parsed = {mid: parse_mode_file(base / f"{mid}.txt") for mid, _ in MODES}

    print("# v0.9.1 five-mode benchmark — CUDA vs Vulkan, standard vs parallel-Huffman JPEG")
    print()
    print(
        "Generated by `scripts/bench_v091.sh` + `scripts/aggregate_v091.py` "
        "from per-mode output of `tests/bench_corpus.sh`."
    )
    print()
    print(
        "Cells show `mean±stddev` in milliseconds.  "
        "`PDF_RASTER_HUFFMAN_THRESHOLD=0` forces every eligible JPEG through the "
        "parallel-Huffman GPU path (C-huff / V-huff).  "
        "V-std has the Huffman path dormant (`threshold=u32::MAX`) so JPEGs fall "
        "through to zune-jpeg on the CPU.  "
        "Ratio columns: C-huff/A, V-huff/A, V-huff/C-huff (< 1.0 = Vulkan Huffman wins)."
    )
    print()

    mode_headers = " | ".join(label for _, label in MODES)
    print(f"| Corpus | {mode_headers} | C-huff/A | V-huff/A | V-huff/C-huff | Flags |")
    sep = " | ".join("---" for _ in MODES)
    print(f"| --- | {sep} | --- | --- | --- | --- |")

    vh_wins = 0

    for slug, label in CORPORA:
        cells = []
        flags_parts = []
        for mid, _ in MODES:
            entry = parsed[mid].get(slug)
            cells.append(entry["cell"] if entry else "—")
            if entry and entry["flags"]:
                flags_parts.append(f"{mid}:{entry['flags']}")

        a_mean    = (parsed["A"].get(slug)      or {}).get("mean")
        ch_mean   = (parsed["C-huff"].get(slug) or {}).get("mean")
        vh_mean   = (parsed["V-huff"].get(slug) or {}).get("mean")

        ch_a   = ratio_cell(ch_mean, a_mean)
        vh_a   = ratio_cell(vh_mean, a_mean)
        vh_ch  = ratio_cell(vh_mean, ch_mean)

        if vh_mean is not None and ch_mean is not None and vh_mean <= ch_mean:
            vh_wins += 1

        cell_str  = " | ".join(cells)
        flags_str = " ".join(flags_parts)
        print(f"| {label} | {cell_str} | {ch_a} | {vh_a} | {vh_ch} | {flags_str} |")

    print()

    # ── V-std vs V-huff: cost of Huffman dispatch on Vulkan ──────────────────
    print("## Vulkan: parallel-Huffman vs CPU JPEG (V-huff / V-std)")
    print()
    print("V-huff/V-std < 1.0 means the GPU Huffman path is faster than CPU decode on Vulkan.")
    print()
    print("| Corpus | V-std | V-huff | V-huff/V-std |")
    print("| --- | --- | --- | --- |")
    for slug, label in CORPORA:
        vs = (parsed["V-std"].get(slug)  or {}).get("mean")
        vh = (parsed["V-huff"].get(slug) or {}).get("mean")
        vs_cell = (parsed["V-std"].get(slug)  or {}).get("cell", "—")
        vh_cell = (parsed["V-huff"].get(slug) or {}).get("cell", "—")
        print(f"| {label} | {vs_cell} | {vh_cell} | {ratio_cell(vh, vs)} |")

    print()

    # ── C-std vs C-huff: cost of Huffman dispatch on CUDA ────────────────────
    print("## CUDA: parallel-Huffman vs nvJPEG (C-huff / C-std)")
    print()
    print("C-huff/C-std < 1.0 means the GPU Huffman path is faster than nvJPEG on CUDA.")
    print()
    print("| Corpus | C-std | C-huff | C-huff/C-std |")
    print("| --- | --- | --- | --- |")
    for slug, label in CORPORA:
        cs = (parsed["C-std"].get(slug)  or {}).get("mean")
        ch = (parsed["C-huff"].get(slug) or {}).get("mean")
        cs_cell = (parsed["C-std"].get(slug)  or {}).get("cell", "—")
        ch_cell = (parsed["C-huff"].get(slug) or {}).get("cell", "—")
        print(f"| {label} | {cs_cell} | {ch_cell} | {ratio_cell(ch, cs)} |")

    print()

    # ── CPU regression ────────────────────────────────────────────────────────
    print("## CPU regression vs v0.9.0 mode A")
    print()
    print("| Corpus | v0.9.0 A | v0.9.1 A | Δ |")
    print("| --- | --- | --- | --- |")
    regress_fail = 0
    for slug, label in CORPORA:
        baseline = V090_MODE_A.get(slug)
        entry = parsed["A"].get(slug)
        if baseline is None or entry is None:
            print(f"| {label} | — | — | — |")
            continue
        cur = entry["mean"]
        delta_pct = (cur - baseline) / baseline * 100
        flag = " **REGRESS**" if delta_pct > 5.0 else ""
        if delta_pct > 5.0:
            regress_fail += 1
        print(f"| {label} | {baseline}ms | {cur}ms | {delta_pct:+.1f}%{flag} |")

    print()
    print("## Summary")
    print()
    print(f"- Vulkan Huffman ≤ CUDA Huffman on {vh_wins}/10 corpora")
    print(f"- CPU no regression > 5% vs v0.9.0 mode A: "
          f"{'PASS' if regress_fail == 0 else f'FAIL ({regress_fail} regressions)'}")
    print()
    print(
        "Note: `PDF_RASTER_HUFFMAN_THRESHOLD=0` forces dispatch for benchmarking.  "
        "Production default is `GPU_JPEG_HUFFMAN_THRESHOLD_PX = u32::MAX` — the "
        "parallel-Huffman path is not auto-enabled until the crossover is confirmed."
    )
    return 0 if regress_fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "bench/v091"))
