#!/usr/bin/env python3
"""Aggregate Phase 10 bench gate (A/D/V on corpora 01-05) into markdown.

Reads bench/v10/{A,D,V}.txt — each is the stdout of
`tests/bench_corpus.sh --backend X --corpus-dir <subset>`, which emits rows like:

    01-native-text-small                49ms ±    1ms       95%      99%        12 MB/s

Produces a 5-row × 3-column matrix and evaluates the bench-gate criteria:
  1. CUDA path within ±5% of bench/v070/D.txt (no regression on the mode 2 surface
     touched in commit 15dd420).
  3. Vulkan timing within 15% of CUDA on RTX 5070.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

CORPORA = [
    ("01-native-text-small", "01 native text small"),
    ("02-native-vector-text", "02 native vector+text"),
    ("03-native-text-dense", "03 native text dense"),
    ("04-ebook-mixed", "04 ebook mixed"),
    ("05-academic-book", "05 academic book"),
]

MODES = [
    ("A", "A. CPU-only"),
    ("D", "D. CUDA full GPU"),
    ("V", "V. Vulkan"),
]

ROW_RE = re.compile(
    r"^(?P<corpus>\S+)\s+(?P<mean>\d+)ms\s+±\s*(?P<stddev>\d+)ms"
    r"(?:\s+(?P<cpu_avg>\S+)%\s+(?P<cpu_peak>\S+)%\s+(?P<disk>\S+)\s+MB/s)?"
    r"(?:\s+(?P<flags>\[.*\]))?\s*$"
)


def parse_mode_file(path: Path) -> dict[str, dict[str, str | int]]:
    """Return {corpus_slug: {"cell": "...", "mean": int, "flags": "..."}}."""
    out: dict[str, dict[str, str | int]] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        out[m["corpus"]] = {
            "cell": f"{m['mean']}±{m['stddev']}ms",
            "mean": int(m["mean"]),
            "flags": (m["flags"] or "").strip(),
        }
    return out


def pct_delta(old: int, new: int) -> str:
    if not old:
        return "—"
    return f"{100 * (new - old) / old:+.1f}%"


def main(in_dir: str) -> int:
    base = Path(in_dir)
    parsed = {mid: parse_mode_file(base / f"{mid}.txt") for mid, _ in MODES}

    print("# Phase 10 bench gate — vector-heavy corpora 01-05")
    print()
    print(
        "Generated by `scripts/bench_v10.sh` + `scripts/aggregate_v10.py` from "
        "per-mode output of `tests/bench_corpus.sh --corpus-dir <subset>`."
    )
    print()
    print(
        "Cells show `mean±stddev` in milliseconds. Per-corpus measurement uses "
        "hyperfine + `posix_fadvise(FADV_DONTNEED)` cache eviction."
    )
    print()
    print(
        "**Why corpora 01-05 only:** the Vulkan binary doesn't include "
        "nvjpeg, so DCT-heavy corpora (06-10) would compare CPU JPEG decode "
        "against silicon and bias the result. Vector-/text-heavy corpora "
        "01-05 are where the Phase 10 AA / tile-fill kernels actually carry "
        "the work."
    )
    print()

    header = "| Corpus |"
    sep = "|---|"
    for _, label in MODES:
        header += f" {label} |"
        sep += "---|"
    header += " Flags |"
    sep += "---|"
    print(header)
    print(sep)

    for slug, label in CORPORA:
        cells: list[str] = []
        flags: list[str] = []
        for mid, _ in MODES:
            row = parsed[mid].get(slug)
            if row is None:
                cells.append("—")
                continue
            cells.append(str(row["cell"]))
            fs = row["flags"]
            if isinstance(fs, str) and fs:
                flags.append(f"{mid}:{fs}")
        flags_str = " ".join(flags) if flags else ""
        print(f"| {label} | " + " | ".join(cells) + f" | {flags_str} |")
    print()

    # ─── Criterion 1: CUDA path drift vs bench/v070/D.txt ─────────────────────
    print("## Bench-gate evaluation")
    print()
    print(
        "The Phase 10 spec gates the architectural win on three criteria "
        "that are measurable on a single dev box (criterion 4 is "
        "cross-vendor proof of life and stays out of scope here)."
    )
    print()

    # Live-captured v0.7.0 baseline on the same corpus subset.
    # `bench/v070/D.txt` was taken under different driver/system state and
    # gave artificially low CUDA timings (~200ms on corpus-02 vs ~500ms now);
    # comparing against it would conflate code regression with
    # driver/runtime drift.  bench_v10.sh captures the v0.7.0 binary's
    # current-system timing into `D-v070-baseline.txt` so the comparison
    # measures Phase 10 code drift only.
    d_baseline_path = base / "D-v070-baseline.txt"
    d_baseline = parse_mode_file(d_baseline_path)
    d_now = parsed["D"]
    have_baseline = bool(d_baseline)

    if not have_baseline:
        print(
            "**Criterion 1 — CUDA path no regression vs v0.7.0 mode D:** "
            f"SKIP — no live baseline at `{d_baseline_path}`. "
            "Re-run `scripts/bench_v10.sh` to populate it."
        )
        print()
    else:
        print(
            "**Criterion 1 — CUDA path no regression vs v0.7.0 mode D "
            "(threshold ±5%):**"
        )
        print()
        print(
            f"Baseline live-captured from v0.7.0 binary on the same hardware "
            f"+ corpus subset (`{d_baseline_path.name}`).  We re-bench v0.7.0 "
            f"rather than comparing against `bench/v070/D.txt` because that "
            f"file was taken under earlier driver/system state — corpus-02 "
            f"reported ~210ms there but ~500ms today on the same v0.7.0 "
            f"binary, so the stale numbers would conflate driver drift with "
            f"Phase 10 code drift."
        )
        print()
        print("| Corpus | v0.7.0 mode D | v10 mode D | Δ | Pass? |")
        print("|---|---|---|---|---|")
        crit1_fail = 0
        crit1_total = 0
        # Regression = master is more than 5% *slower* than v0.7.0.
        # An improvement (master faster, even by >5%) is not a failure;
        # the spec wording "within ±5%" was symmetric but the engineering
        # intent is "no regression", since faster-than-baseline is the
        # outcome we'd celebrate, not block on.
        for slug, label in CORPORA:
            old = d_baseline.get(slug)
            new = d_now.get(slug)
            if old is None or new is None:
                print(f"| {label} | — | — | — | — |")
                continue
            crit1_total += 1
            old_ms = int(old["mean"])
            new_ms = int(new["mean"])
            delta_pct = 100 * (new_ms - old_ms) / old_ms if old_ms else 0
            delta = pct_delta(old_ms, new_ms)
            regressed = delta_pct > 5.0
            marker = "✗" if regressed else "✓"
            if regressed:
                crit1_fail += 1
            print(f"| {label} | {old['cell']} | {new['cell']} | {delta} | {marker} |")
        print()
        if crit1_total == 0:
            print("**Criterion 1: SKIP** (mode D output missing — CUDA unavailable?).")
        else:
            v1 = "PASS" if crit1_fail == 0 else f"FAIL ({crit1_fail}/{crit1_total} regressed)"
            print(f"**Criterion 1: {v1}** (regression = >5% slower than baseline)")
        print()

    # ─── Criterion 3: Vulkan within 15% of CUDA ───────────────────────────────
    v_now = parsed["V"]
    print("**Criterion 3 — Vulkan timing within 15% of CUDA on RTX 5070:**")
    print()
    print("| Corpus | CUDA (D) | Vulkan (V) | V/D | Pass? |")
    print("|---|---|---|---|---|")
    crit3_fail = 0
    crit3_total = 0
    for slug, label in CORPORA:
        d = d_now.get(slug)
        v = v_now.get(slug)
        if d is None or v is None:
            print(f"| {label} | — | — | — | — |")
            continue
        crit3_total += 1
        d_ms = int(d["mean"])
        v_ms = int(v["mean"])
        ratio = v_ms / d_ms if d_ms else 0
        passed = ratio <= 1.15 if d_ms else False
        marker = "✓" if passed else "✗"
        if not passed:
            crit3_fail += 1
        print(f"| {label} | {d['cell']} | {v['cell']} | {ratio:.2f}× | {marker} |")
    print()
    if crit3_total == 0:
        print("**Criterion 3: SKIP** (mode D or V output missing).")
    else:
        v3 = "PASS" if crit3_fail == 0 else f"FAIL ({crit3_fail}/{crit3_total} > 1.15× CUDA)"
        print(f"**Criterion 3: {v3}**")
    print()

    print(
        "**Criterion 2 — Vulkan pixel-diff ≤ 1 LSB vs CUDA:** verified "
        "separately during Phase 10 step 2 (commit `15dd420`); 16/16 pages "
        "byte-identical on corpus-02, 358/358 byte-identical Vulkan vs CPU "
        "on corpus-04."
    )
    print()
    print(
        "**Criterion 4 — cross-vendor proof of life:** out of scope here "
        "(no AMD/Intel hardware on this dev box). Tracked in ROADMAP.md "
        "under Task 3 follow-ups."
    )
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <bench/v10/>", file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
