#!/usr/bin/env python3
"""Pivot v0.6.0 GPU baseline mode-files into a markdown matrix.

Reads bench/v060/{A,B,C,D}.txt — each is the stdout of
`tests/bench_corpus.sh --backend X`, which emits rows like:

    01-native-text-small                49ms ±    1ms       95%      99%        12 MB/s
    08-scan-dct-1927                  10715ms ±  142ms       96%      99%       205 MB/s  [high-σ 18%]

Emits a markdown table with one row per corpus and one mean±stddev cell
per mode A/B/C/D, plus a flags column collecting any quality flags
across modes.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

CORPORA = [
    ("01-native-text-small", "01 native text small"),
    ("02-native-vector-text", "02 native vector+text"),
    ("03-native-text-dense", "03 native text dense"),
    ("04-ebook-mixed", "04 ebook mixed"),
    ("05-academic-book", "05 academic book"),
    ("06-modern-layout-dct", "06 modern layout DCT"),
    ("07-journal-dct-heavy", "07 journal DCT heavy"),
    ("08-scan-dct-1927", "08 scan DCT 1927 (baseline JPEG)"),
    ("09-scan-dct-1836", "09 scan DCT 1836 (progressive JPEG)"),
    ("10-scan-jbig2-jpx", "10 scan JBIG2+JPX"),
]

MODES = [
    ("A", "A. CPU-only"),
    ("B", "B. VA-API"),
    ("C", "C. nvJPEG"),
    ("D", "D. Full GPU"),
]

# bench_corpus.sh format:
#   %-32s  %9dms ±%5dms  %7s%%  %7s%%  %8s MB/s  %s
ROW_RE = re.compile(
    r"^(?P<corpus>\S+)\s+(?P<mean>\d+)ms\s+±\s*(?P<stddev>\d+)ms"
    r"(?:\s+(?P<cpu_avg>\S+)%\s+(?P<cpu_peak>\S+)%\s+(?P<disk>\S+)\s+MB/s)?"
    r"(?:\s+(?P<flags>\[.*\]))?\s*$"
)


def parse_mode_file(path: Path) -> dict[str, dict[str, str]]:
    """Return {corpus_slug: {"cell": "Nms±Mms", "flags": "..."}}."""
    out: dict[str, dict[str, str]] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        out[m["corpus"]] = {
            "cell": f"{m['mean']}±{m['stddev']}ms",
            "flags": (m["flags"] or "").strip(),
        }
    return out


def main(in_dir: str) -> int:
    base = Path(in_dir)
    parsed = {mid: parse_mode_file(base / f"{mid}.txt") for mid, _ in MODES}

    print("# v0.6.0 GPU baseline — full corpus matrix")
    print()
    print(
        "Generated by `scripts/bench_v060.sh` + `scripts/aggregate_v060.py` "
        "from per-mode output of `tests/bench_corpus.sh`."
    )
    print()
    print(
        "Cells show `mean±stddev` in milliseconds. Per-corpus measurement uses "
        "hyperfine + `posix_fadvise(FADV_DONTNEED)` cache eviction. CPU% / disk "
        "MB/s / quality flags from the source files are summarised in the "
        "Flags column."
    )
    print()
    header = "| Corpus |"
    sep = "|---|"
    for _, label in MODES:
        header += f" {label} |"
        sep += "---|"
    header += " Flags |"
    sep += "---|"
    print(header)
    print(sep)

    for slug, label in CORPORA:
        cells: list[str] = []
        flags: list[str] = []
        for mid, _ in MODES:
            row = parsed[mid].get(slug)
            if row is None:
                cells.append("—")
            else:
                cells.append(row["cell"])
                if row["flags"]:
                    flags.append(f"{mid}:{row['flags']}")
        flags_str = " ".join(flags) if flags else ""
        row_str = f"| {label} | " + " | ".join(cells) + f" | {flags_str} |"
        print(row_str)

    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <bench/v060/>", file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
