#!/usr/bin/env bash
# Aggregate v0.6.0 GPU baseline hyperfine JSON files into a markdown table.
#
# Usage: scripts/aggregate_v060.sh <input_dir> <output_md>
# Example: scripts/aggregate_v060.sh bench/v060 bench/v060/results.md
#
# Expects files named <corpus>-<mode>.json where:
#   corpus ∈ corpus-01 .. corpus-10
#   mode   ∈ cpu, vaapi, nvjpeg, full
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <input_dir> <output_md>" >&2
  exit 2
fi

IN_DIR="$1"
OUT_MD="$2"

CORPORA=(
  "corpus-01:01 native text small"
  "corpus-02:02 native vector+text"
  "corpus-03:03 native text dense"
  "corpus-04:04 ebook mixed"
  "corpus-05:05 academic book"
  "corpus-06:06 modern layout DCT"
  "corpus-07:07 journal DCT heavy"
  "corpus-08:08 scan DCT 1927 (baseline JPEG)"
  "corpus-09:09 scan DCT 1836 (progressive JPEG)"
  "corpus-10:10 scan JBIG2+JPX"
)
MODES=(cpu vaapi nvjpeg full)

# Read mean*1000 (ms) from a hyperfine JSON; "—" if missing or parse error.
read_mean_ms() {
  local f="$1"
  if [[ ! -f "$f" ]]; then
    echo "—"
    return
  fi
  jq -r '
    .results[0]
    | (.mean * 1000 | floor) as $m
    | (.stddev * 1000 | floor) as $s
    | "\($m)±\($s)ms"
  ' "$f" 2>/dev/null || echo "—"
}

{
  echo "# v0.6.0 GPU baseline — full corpus matrix"
  echo
  echo "Generated by \`scripts/aggregate_v060.sh\` from hyperfine JSON in \`$IN_DIR\`."
  echo
  echo "Cells show \`mean±stddev\` in milliseconds, hyperfine \`--warmup 3 --runs 8\`,"
  echo "cold cache between cells, 150 DPI, 24 threads, RAM-backed output."
  echo
  echo "| Corpus | A. CPU-only | B. VA-API | C. nvJPEG | D. Full GPU |"
  echo "|---|---|---|---|---|"
  for entry in "${CORPORA[@]}"; do
    slug="${entry%%:*}"
    label="${entry#*:}"
    row="| $label |"
    for mode in "${MODES[@]}"; do
      cell=$(read_mean_ms "$IN_DIR/${slug}-${mode}.json")
      row="$row $cell |"
    done
    echo "$row"
  done
} > "$OUT_MD"

echo "Wrote $OUT_MD"
