#!/usr/bin/env python3
"""Pivot v0.8.0 mode-files into a markdown matrix with gate evaluation.

Reads bench/v080/{A,D,H}.txt — each is the stdout of
`tests/bench_corpus.sh --backend X`, which emits rows like:

    01-native-text-small          49ms ±   1ms   95%   99%    12 MB/s
    08-scan-dct-1927           10715ms ± 142ms   96%   99%   205 MB/s  [high-σ 18%]
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

CORPORA = [
    ("01-native-text-small",    "01 native text small"),
    ("02-native-vector-text",   "02 native vector+text"),
    ("03-native-text-dense",    "03 native text dense"),
    ("04-ebook-mixed",          "04 ebook mixed"),
    ("05-academic-book",        "05 academic book"),
    ("06-modern-layout-dct",    "06 modern layout DCT"),
    ("07-journal-dct-heavy",    "07 journal DCT heavy"),
    ("08-scan-dct-1927",        "08 scan DCT 1927 (baseline JPEG)"),
    ("09-scan-dct-1836",        "09 scan DCT 1836 (progressive JPEG)"),
    ("10-scan-jbig2-jpx",       "10 scan JBIG2+JPX"),
]

MODES = [
    ("A", "A. CPU-only"),
    ("D", "D. Full GPU (nvjpeg)"),
    ("H", "H. GPU Huffman JPEG"),
]

ROW_RE = re.compile(
    r"^(?P<corpus>\S+)\s+(?P<mean>\d+)ms\s+±\s*(?P<stddev>\d+)ms"
    r"(?:\s+(?P<cpu_avg>\S+)%\s+(?P<cpu_peak>\S+)%\s+(?P<disk>\S+)\s+MB/s)?"
    r"(?:\s+(?P<flags>\[.*\]))?\s*$"
)

V070_MODE_A = {
    "01-native-text-small":   55,
    "02-native-vector-text":  22,
    "03-native-text-dense":  297,
    "04-ebook-mixed":        636,
    "05-academic-book":     1069,
    "06-modern-layout-dct": 2700,
    "07-journal-dct-heavy":  722,
    "08-scan-dct-1927":     1994,
    "09-scan-dct-1836":     2481,
    "10-scan-jbig2-jpx":   17938,
}


def parse_mode_file(path: Path) -> dict[str, dict]:
    out: dict[str, dict] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        out[m["corpus"]] = {
            "cell": f"{m['mean']}±{m['stddev']}ms",
            "mean": int(m["mean"]),
            "flags": (m["flags"] or "").strip(),
        }
    if not out:
        print(f"warning: {path} exists but yielded no parseable rows", file=sys.stderr)
    return out


def ratio_cell(num: int | None, den: int | None) -> str:
    if num is None or den is None or den == 0:
        return "—"
    return f"{num / den:.2f}×"


def main(in_dir: str) -> int:
    base = Path(in_dir)
    parsed = {mid: parse_mode_file(base / f"{mid}.txt") for mid, _ in MODES}

    print("# v0.8.0 gpu-jpeg-huffman gate — full corpus run")
    print()
    print(
        "Generated by `scripts/bench_v080.sh` + `scripts/aggregate_v080.py` "
        "from per-mode output of `tests/bench_corpus.sh`."
    )
    print()
    print(
        "Cells show `mean±stddev` in milliseconds. "
        "H/A column is mode H divided by mode A (< 1.0 = GPU wins)."
    )
    print()

    # Header
    mode_headers = " | ".join(label for _, label in MODES)
    print(f"| Corpus | {mode_headers} | H/A ratio | Flags |")
    sep = "|".join("---|" for _ in MODES)
    print(f"|---|{sep}---|---|")

    gate_wins = 0
    gate_corpora = {"06-modern-layout-dct", "07-journal-dct-heavy",
                    "08-scan-dct-1927", "09-scan-dct-1836"}

    rows = []
    for slug, label in CORPORA:
        cells = []
        flags_parts = []
        for mid, _ in MODES:
            entry = parsed[mid].get(slug)
            cells.append(entry["cell"] if entry else "—")
            if entry and entry["flags"]:
                flags_parts.append(f"{mid}:{entry['flags']}")

        a_mean = (parsed["A"].get(slug) or {}).get("mean")
        h_mean = (parsed["H"].get(slug) or {}).get("mean")
        ratio = ratio_cell(h_mean, a_mean)

        if slug in gate_corpora and h_mean is not None and a_mean is not None:
            if h_mean <= 0.7 * a_mean:
                gate_wins += 1
                flags_parts.append("H:gate-win")

        cell_str = " | ".join(cells)
        flags_str = " ".join(flags_parts)
        rows.append(f"| {label} | {cell_str} | {ratio} | {flags_str} |")

    for row in rows:
        print(row)

    print()
    print("## Regression vs v0.7.0 mode A")
    print()
    print("| Corpus | v0.7.0 A | v0.8.0 A | Δ |")
    print("|---|---|---|---|")
    regress_fail = 0
    for slug, label in CORPORA:
        baseline = V070_MODE_A.get(slug)
        entry = parsed["A"].get(slug)
        if baseline is None or entry is None:
            print(f"| {label} | — | — | — |")
            continue
        cur = entry["mean"]
        delta_pct = (cur - baseline) / baseline * 100
        flag = " **REGRESS**" if delta_pct > 5.0 else ""
        if delta_pct > 5.0:
            regress_fail += 1
        print(f"| {label} | {baseline}ms | {cur}ms | {delta_pct:+.1f}%{flag} |")

    print()
    print("## Gate evaluation")
    print()
    gate_pass = gate_wins >= 1
    regress_pass = regress_fail == 0
    overall = gate_pass and regress_pass
    print(f"- Mode H ≤ 0.7× mode A on corpora 06-09: "
          f"{'PASS' if gate_pass else 'FAIL'} ({gate_wins}/4 corpora, 1 required)")
    print(f"- No corpus regresses > 5% vs v0.7.0 mode A: "
          f"{'PASS' if regress_pass else 'FAIL'} ({regress_fail} failures)")
    print()
    print(f"**Overall gate: {'PASS — feature flag may be lifted' if overall else 'FAIL — feature stays behind flag'}**")
    return 0 if overall else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "bench/v080"))
